#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/pcon/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

xrandr --output HDMI-1 --left-of DVI-I-1 --output DVI-I-1 --primary&
nm-applet --sm-disable &
clementine&
synergy-core --server -c /home/pcon/Dropbox/config/work/synergy.conf &
dropbox start&
synology-cloud-station-drive&
pasystray&
#autokey-gtk&

#gnome-power-manager &
#gnome-do &
#gnome-sound-applet&
#fbsetroot -solid black&
#/usr/lib64/xfce4/notifyd/xfce4-notifyd&

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/pcon/.fluxbox/log"